 
serviceName: |
  Name of the kubernetes service which Ingress will use as backend to serve the request.
  The service must already be configured as a LoadBalancer, NodePort, or ClusterIP.
  See the documentation [here](https://docs.duplocloud.com/docs/aws/quick-start/step-6-create-a-load-balancer)
port: |
  Backend port on the Kubernetes service that the Ingress will route traffic to.
  This value must be provided as a string (for example, "443"), not a number..
host:  If a host is provided (for e.g. example.com, foo.bar.com), the rules apply to that host.
path: Specify the path (for e.g. /api /v1/api/)for path-based routing. If a host is specified, both the host and path must match the incoming request.
pathType: |
  Each path in an Ingress is required to have a corresponding path type. Paths that do not include an explicit pathType will fail validation. There are three supported path types:

  1. *ImplementationSpecific*: Matching behavior is determined by the IngressClass and may behave like Prefix or Exact path types.
  2. *Exact*: Matches the URL path exactly and with case sensitivity.
  3. *Prefix*: Matches based on a URL path prefix split by /. Matching is case sensitive and done on a path element by element basis. A path element refers to the list of labels in the path split by the / separator. A request is a match for path p if every p is an element-wise prefix of p of the request path. 

