name: JSON Lint
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Check JSON Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Run JSON Lint on all JSON files
        run: |
          find . -name "*.json" -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file"
            jq . "$file" > /dev/null
          done
